# Here n=148 and k=3, so p=148148148.Lkjgjh
# super_digit(p) ⇒  super_digit(148148148)
#                        ⇒ super_digit(1+4+8+1+4+8+1+4+8)
#                        ⇒ super_digit(39)
#                        ⇒ super_digit(3+9)
#                        ⇒ super_digit(12)


Challenge name:-    Palindrome Pairs
Description:-
Given a list of unique words. Final all pairs of distinct words (i, j) 
in the given list so that the concatenation of the two words, 
i.e. words[i] +words[j] is a palindrome.
Problem statement:-
Sample input:-
list_string=[“bat”, “tab”, “cat”]
Output:
[ [0 ,1] ,[1, 0]]
Sample input:
list_string=[“dog” ,”cow”, “tap”, “god”, “pat”]
Output:
[ [0,3], [2,4],[3, 0],[4,2]]

Sample input:
list1_string=[ “abcd”, “dcba”, “lls”, “s”, “ssslll”]
Output:
[ [0,1], [1,0],[2,4],[3,2] ]

